// Auto-generated by create-service-indexes.sh
// Re-exports the default list of ServicePackage items for this service.
// Keep service packages in "./video-production-packages.ts" and import this folder as the service root.
//
// Example consumer:
//   import packages from "@/data/packages/Services/video-production";

export { default } from "./video-production-packages";
