// Auto-generated by create-service-indexes.sh
// Re-exports the default list of ServicePackage items for this service.
// Keep service packages in "./web-development-packages.ts" and import this folder as the service root.
//
// Example consumer:
//   import packages from "@/data/packages/Services/web-development";

export { default } from "./web-development-packages";
