// src/packages/sections/PackageDetailExtras/PackageDetailExtras.tsx
"use client";

import * as React from "react";
import Divider from "@/components/ui/atoms/Divider/Divider";
import styles from "./PackageDetailExtras.module.css";

/* -------------------------------------------------------------------------- */
/*                                    Types                                   */
/* -------------------------------------------------------------------------- */

export type TimelineItem = {
  /** Short title of the step, e.g., "Setup" */
  title: string;
  /** Supporting detail, e.g., "3–5 business days" */
  note?: string;
  /** Optional id (autogenerated otherwise) */
  id?: string;
};

export type LegacyTimeline = {
  setup?: string;
  launch?: string;
  ongoing?: string;
};

export type PackageDetailExtrasProps = {
  /**
   * Flexible timeline blocks (1–5). If omitted, we’ll try to derive from `timeline` (legacy shape).
   */
  timelineBlocks?: TimelineItem[];

  /**
   * Legacy timeline shape (optional). If `timelineBlocks` is provided, it wins.
   */
  timeline?: LegacyTimeline;

  /**
   * Optional Limits & Ethics bullets. Renders only if non-empty.
   */
  ethics?: string[];

  /**
   * Optional separate "limits" bullets (out-of-scope items). If provided,
   * they are rendered under the same "Limits & Ethics" section as a second list.
   */
  limits?: string[];

  /* ------------------------ OVERRIDABLE COPY (NEW) ----------------------- */
  /** Section 1: Timeline & Turnaround */
  timelineTitle?: string;     // default: "Timeline & Turnaround"
  timelineTagline?: string;   // default: "How we get you live and iterating."

  /** Section 2: Limits & Ethics */
  ethicsTitle?: string;       // default: "Limits & Ethics"
  ethicsTagline?: string;     // default: "Boundaries that keep outcomes fair and compliant."

  /* -------- Back-compat aliases (if callers still pass these names) ------ */
  /** @deprecated Use timelineTitle */
  timelineHeading?: string;
  /** @deprecated Use ethicsTitle */
  ethicsHeading?: string;

  /* ------------------------------ Utilities ------------------------------ */
  className?: string;
  style?: React.CSSProperties;
  id?: string;
  "data-testid"?: string;
  ariaLabel?: string;
};

/* -------------------------------------------------------------------------- */
/*                                 Component                                  */
/* -------------------------------------------------------------------------- */

export default function PackageDetailExtras({
  timelineBlocks,
  timeline,
  ethics,
  limits,

  // New copy overrides with sensible defaults
  timelineTitle,
  timelineTagline,
  ethicsTitle,
  ethicsTagline,

  // Back-compat aliases (map to new names if supplied)
  timelineHeading,
  ethicsHeading,

  className,
  style,
  id,
  "data-testid": testId = "package-detail-extras",
  ariaLabel,
}: PackageDetailExtrasProps) {
  /* -------------------------------- Defaults ------------------------------ */
  const finalTimelineTitle =
    timelineTitle ?? timelineHeading /* back-compat */ ?? "Timeline & Turnaround";
  const finalTimelineTagline =
    timelineTagline ?? "How we get you live and iterating.";

  const finalEthicsTitle =
    ethicsTitle ?? ethicsHeading /* back-compat */ ?? "Limits & Ethics";
  const finalEthicsTagline =
    ethicsTagline ?? "Boundaries that keep outcomes fair and compliant.";

  /* --------------------------- Normalize timeline ------------------------- */
  const steps: TimelineItem[] = React.useMemo(() => {
    const fromBlocks =
      (timelineBlocks ?? [])
        .filter(Boolean)
        .map((b) => ({
          title: (b?.title ?? "").trim(),
          note: b?.note?.trim(),
          id: b?.id,
        }))
        .filter((b) => b.title.length > 0) || [];

    if (fromBlocks.length > 0) return fromBlocks.slice(0, 5);

    // Legacy fallbacks
    const derived: TimelineItem[] = [];
    if (timeline?.setup) derived.push({ title: "Setup", note: timeline.setup });
    if (timeline?.launch) derived.push({ title: "Launch", note: timeline.launch });
    if (timeline?.ongoing) derived.push({ title: "Ongoing", note: timeline.ongoing });

    return derived.slice(0, 5);
  }, [timelineBlocks, timeline]);

  const hasTimeline = steps.length > 0;
  const hasEthics = (ethics?.filter(Boolean).length ?? 0) > 0;
  const hasLimits = (limits?.filter(Boolean).length ?? 0) > 0;

  if (!hasTimeline && !hasEthics && !hasLimits) return null;

  /* -------------------------------- Render -------------------------------- */
  return (
    <section
      id={id}
      className={[styles.wrap, className].filter(Boolean).join(" ")}
      style={style}
      aria-label={ariaLabel ?? "Additional package details"}
      data-testid={testId}
    >
      {/* ============================== TIMELINE ============================== */}
      {hasTimeline && (
        <section className={styles.block} aria-label="Timeline / Turnaround">
          {/* Header group: (Title + Divider) wrapped together, Tagline directly under, then all wrapped */}
          <header className={styles.hgroup}>
            <div className={styles.hpair}>
              <h2 className={styles.hTitle}>{finalTimelineTitle}</h2>
              <Divider className={styles.hRule} />
            </div>
            {finalTimelineTagline ? (
              <div className={styles.hTaglineWrap}>
                <p className={styles.hTagline}>{finalTimelineTagline}</p>
              </div>
            ) : null}
          </header>

          <ol className={styles.timeline} aria-label="Project timeline">
            {steps.map((step, i) => {
              const key = step.id ?? `${step.title}-${i}`;
              const index = i + 1;
              const isLast = i === steps.length - 1;
              return (
                <React.Fragment key={key}>
                  <li
                    className={styles.step}
                    aria-label={`${step.title}${step.note ? ` — ${step.note}` : ""}`}
                  >
                    <div className={styles.stepCard}>
                      <div className={styles.stepIndex} aria-hidden="true">
                        {index}
                      </div>
                      <div className={styles.stepBody}>
                        <div className={styles.stepTitle}>{step.title}</div>
                        {step.note ? <p className={styles.stepNote}>{step.note}</p> : null}
                      </div>
                    </div>
                  </li>

                  {/* Connector (arrow) between steps */}
                  {!isLast && (
                    <li className={styles.connector} aria-hidden="true">
                      <span className={styles.line} />
                      <span className={styles.chevron} />
                    </li>
                  )}
                </React.Fragment>
              );
            })}
          </ol>
        </section>
      )}

      {/* =========================== LIMITS & ETHICS ========================== */}
      {(hasEthics || hasLimits) && (
        <section className={styles.block} aria-label="Limits and Ethics">
          {/* Header group: (Title + Divider) wrapped together, Tagline directly under, then all wrapped */}
          <header className={styles.hgroup}>
            <div className={styles.hpair}>
              <h2 className={styles.hTitle}>{finalEthicsTitle}</h2>
              <Divider className={styles.hRule} />
            </div>
            {finalEthicsTagline ? (
              <div className={styles.hTaglineWrap}>
                <p className={styles.hTagline}>{finalEthicsTagline}</p>
              </div>
            ) : null}
          </header>

          {hasEthics && (
            <ul className={styles.ethicsList} aria-label="Ethics">
              {ethics!.filter(Boolean).map((e, i) => (
                <li key={`ethic-${i}`}>{e}</li>
              ))}
            </ul>
          )}

          {hasLimits && (
            <ul className={styles.limitsList} aria-label="Limits">
              {limits!.filter(Boolean).map((l, i) => (
                <li key={`limit-${i}`}>{l}</li>
              ))}
            </ul>
          )}
        </section>
      )}
    </section>
  );
}
