// Auto-generated by create-addon-indexes.sh
// Exports a default AddOn[] for this service folder.
// Each file in this directory should export a default AddOn object.

import type { AddOn } from "../../_types/packages.types";


const LIST: AddOn[] = [

];

export const MAP: Record<string, AddOn> = Object.fromEntries(LIST.map(a => [a.id, a]));

export default LIST;

// (Optional) Re-export the type for convenience
export type { AddOn } from "../../_types/packages.types";
