#!/usr/bin/env bash
# scripts/bootstrap-featured-indexes.sh
# Create/overwrite index.ts in each Featured/* directory so imports resolve.
# If slugs.txt exists in a folder, its lines seed the array; else an empty stub is written.
#
# Usage:
#   chmod +x scripts/bootstrap-featured-indexes.sh
#   ./scripts/bootstrap-featured-indexes.sh          # create only if missing
#   ./scripts/bootstrap-featured-indexes.sh --force  # overwrite existing

set -euo pipefail

FORCE=0
if [[ "${1:-}" == "--force" || "${1:-}" == "-f" ]]; then
  FORCE=1
fi

ROOT="src/data/packages/Featured"
DIRS=(
  "${ROOT}/content-production-featured"
  "${ROOT}/lead-generation-featured"
  "${ROOT}/marketing-featured"
  "${ROOT}/seo-featured"
  "${ROOT}/video-production-featured"
  "${ROOT}/web-development-featured"
)

emit_ts() {
  local out="$1"
  shift
  local slugs=( "$@" )

  local entries=""
  if [[ ${#slugs[@]} -gt 0 ]]; then
    for s in "${slugs[@]}"; do
      entries+="  \"${s}\",\n"
    done
  fi

  # Write the TS file
  cat > "$out" <<'TS'
// Auto-generated by bootstrap-featured-indexes.sh
// Export a default string[] of curated bundle slugs for this service.
// Add or reorder as needed to control storefront rails.

const SLUGS: string[] = [
TS
  # append the entries block
  printf "%b" "${entries%\\n}\n" >> "$out"
  cat >> "$out" <<'TS'
];

export default SLUGS;

// Optional named export for convenience
export const FEATURED = SLUGS;
TS
}

process_dir() {
  local dir="$1"
  local outfile="${dir}/index.ts"

  mkdir -p "$dir"

  if [[ -f "$outfile" && $FORCE -eq 0 ]]; then
    echo "⚠️  ${outfile} exists — skipped (use --force to overwrite)"
    return
  fi

  # Seed from slugs.txt if present
  local slugs=()
  if [[ -f "${dir}/slugs.txt" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
      line="${line%%\#*}"           # strip trailing comments
      line="$(echo "$line" | xargs)" # trim
      [[ -z "$line" ]] && continue
      slugs+=( "$line" )
    done < "${dir}/slugs.txt"
  fi

  emit_ts "$outfile" "${slugs[@]}"

  if [[ ${#slugs[@]} -gt 0 ]]; then
    echo "✅ wrote ${outfile} (${#slugs[@]} slug(s) from slugs.txt)"
  else
    echo "✅ wrote ${outfile} (empty stub)"
  fi
}

for d in "${DIRS[@]}"; do
  process_dir "$d"
done

echo "🎉 Featured index files bootstrapped."
