// Auto-generated by bootstrap-featured-indexes.sh
// Export a default string[] of curated bundle slugs for this service.
// Add or reorder as needed to control storefront rails.

const SLUGS: string[] = [

];

export default SLUGS;

// Optional named export for convenience
export const FEATURED = SLUGS;
