// src/booking/components/ConsentPolicies/lib/index.ts
// Barrel exports for ConsentPolicies lib utilities

export {
  createPrivacyConsent,
  createTermsConsent,
  createMarketingConsent,
  createCookieConsent,
  createDataProcessingConsent,
  validateConsent,
  validateAllConsents,
  updateConsentStatus,
  getConsentsByStatus,
  getRequiredConsents,
  getOptionalConsents,
  areAllRequiredConsentsAccepted,
  getConsentCompletionRate,
  generateConsentRecord,
  exportConsentData,
  trackConsentEvent,
  createConsentAnalytics,
  createConsentPreferences,
  applyPreferencesToConsents,
  saveConsentsToStorage,
  loadConsentsFromStorage,
  clearConsentsFromStorage,
  saveConsentHistory,
  getBookingConsents,
  getExpiringConsents,
  renewConsentExpiry,
  generateAriaLabel,
  announceConsentChange,
  isValidConsentStatus,
  isValidConsentType,
  isValidPolicyType,
  syncConsentsWithForm,
  extractFormDataFromConsents,
  acceptAllOptionalConsents,
  declineAllOptionalConsents,
  resetAllConsents,
} from './utils';

// Re-export types for convenience
export type {
  ConsentItem,
  ConsentStatus,
  ConsentType,
  PolicyType,
  ConsentAnalytics,
  ConsentPreferences,
  LegalBasis,
  ConsentRecord,
  ConsentValidation,
  PolicyDocument,
  ThirdParty,
  UserRight,
  ConsentExportData,
  ComplianceData,
} from '../ConsentPolicies.types';