// Auto-generated by create-service-indexes.sh
// Re-exports the default list of ServicePackage items for this service.
// Keep service packages in "./seo-services-packages.ts" and import this folder as the service root.
//
// Example consumer:
//   import packages from "@/data/packages/Services/seo-services";

export { default } from "./seo-services-packages";
